# k8s/prod/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incentivize-this-frontend
  name: incentivize-this-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incentivize-this-frontend
  template:
    metadata:
      labels:
        app: incentivize-this-frontend
    spec:
      containers:
      - image: "{{DOCKER_REPO}}/{{FRONTEND_IMAGE_NAME}}:{{TAG}}"
        imagePullPolicy: Always
        name: incentivize-this-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred